# Generated by Django 3.1.5 on 2021-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_clan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clan',
        ),
    ]
