# Generated by Django 3.1.5 on 2021-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_delete_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='zanr',
            field=models.CharField(choices=[('biografija', 'biografija'), ('komedija', 'komedija'), ('drama', 'drama'), ('roman', 'roman')], max_length=200, null=True),
        ),
    ]
